spring.application.name=disciplinetracker

spring.profiles.active=dev

spring.data.mongodb.uri=mongodb://localhost:27017/disciplineTracker

logging.level.org.springframework.web.server.adapter.HttpWebHandlerAdapter=TRACE 
logging.level.org.springframework.web.HttpLogging=TRACE